-- MySQL Script generated by MySQL Workbench
-- Mon May  1 11:59:51 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema J4F
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema J4F
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `J4F` DEFAULT CHARACTER SET utf8 ;
USE `J4F` ;

-- -----------------------------------------------------
-- Table `J4F`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `J4F`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `Login` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(100) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Date` DATETIME NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `J4F`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `J4F`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `J4F`.`Articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `J4F`.`Articles` (
  `idArticles` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(128) NOT NULL,
  `Content` LONGTEXT NOT NULL,
  `Author` VARCHAR(45) NOT NULL DEFAULT 'Admin',
  `Date` DATETIME NULL,
  `category_category_id` INT NOT NULL,
  PRIMARY KEY (`idArticles`, `category_category_id`),
  INDEX `fk_Articles_category_idx` (`category_category_id` ASC),
  CONSTRAINT `fk_Articles_category`
    FOREIGN KEY (`category_category_id`)
    REFERENCES `J4F`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
